spring.application.name=securevaultx-spring-boot

spring.datasource.url=jdbc:mysql://localhost:3306/securevaultx
spring.datasource.username=root
spring.datasource.password=vishal08

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true